### PR TITLE
Clarify key ID is a digest over SPKI

### PR DESCRIPTION
**Pull request by haydentherapper**
The comment said the DER encoding, which is not what RFC6962 specifies.

We noted in root-signing that trusted_root.json's key IDs were over the DER encoding of the key, rather than the SubjectPublicKeyInfo structure, which is the raw key and an OID.

### CODE REVIEW

**Comment by haydentherapper** [comment]
cc @bdehamer @woodruffw 

I'm not sure if you're verifying using trusted_root.json yet - Let me know if so, then we'll need to discuss more. I have an open issue, https://github.com/sigstore/root-signing/issues/759, to update the key IDs.

**Review by znewman01 — DISMISSED** [review]

**Comment by haydentherapper** [comment]
Agreed! I’ll update on Monday

**Comment by bdehamer** [comment]
Just to be clear, we're storing our keys in the `SubjectPublicKeyInfo` format already:
```console
$ echo -n "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEiPSlFi0CmFTfEjCUqF9HuCEcYXNKAaYalIJmBZ8yyezPjTqhxrKBpMnaocVtLJBI1eM3uXnQzQGAJdJ4gs9Fyw==" | base64 -d | openssl asn1parse -inform der -i
    0:d=0  hl=2 l=  89 cons: SEQUENCE
    2:d=1  hl=2 l=  19 cons:  SEQUENCE
    4:d=2  hl=2 l=   7 prim:   OBJECT            :id-ecPublicKey
   13:d=2  hl=2 l=   8 prim:   OBJECT            :prime256v1
   23:d=1  hl=2 l=  66 prim:  BIT STRING
```

I think it's good to clarify the comment in the protobuf, but I believe we're already doing things properly wrt to the IDs we have in the current version of the trusted_root.json.

**Review by znewman01 — COMMENTED** [review]
Can you fix the whitespace? The commit is full of whitespace noise

**Comment by haydentherapper** [comment]
oh whoops, sorry! that was vim's fault

**Comment by haydentherapper** [comment]
There we go, turned off auto formatting proto files...

**Review by bdehamer — APPROVED** [review]

**Review by kommendorkapten — APPROVED** [review]

**Pull request merged**
